2021-04-03 10:40:42,525 ERROR: Exception on /program/Mass Gen [GET] [in a:\projects\match\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "a:\projects\match\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "a:\projects\match\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "A:\projects\match\app\main\routes.py", line 90, in program
    return render_template('program.html', program=program, form=form)
  File "a:\projects\match\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "a:\projects\match\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "a:\projects\match\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "a:\projects\match\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "a:\projects\match\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "A:\projects\match\app\templates\program.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "A:\projects\match\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "A:\projects\match\app\templates\base.html", line 66, in block "content"
    {% block app_content %}{% endblock %}
  File "A:\projects\match\app\templates\program.html", line 11, in block "app_content"
    {% if not current_user.is_following_program(program) %}
  File "A:\projects\match\app\models.py", line 134, in is_following_program
    console.log(self.programs)
NameError: name 'console' is not defined
2021-04-03 10:41:47,775 ERROR: Exception on /program/Mass Gen [GET] [in a:\projects\match\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "a:\projects\match\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "a:\projects\match\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "a:\projects\match\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "A:\projects\match\app\main\routes.py", line 90, in program
    return render_template('program.html', program=program, form=form)
  File "a:\projects\match\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "a:\projects\match\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "a:\projects\match\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "a:\projects\match\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "a:\projects\match\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "A:\projects\match\app\templates\program.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "A:\projects\match\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "a:\projects\match\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "A:\projects\match\app\templates\base.html", line 66, in block "content"
    {% block app_content %}{% endblock %}
  File "A:\projects\match\app\templates\program.html", line 11, in block "app_content"
    {% if not current_user.is_following_program(program) %}
  File "A:\projects\match\app\models.py", line 134, in is_following_program
    return 1
NameError: name 'console' is not defined
2021-04-04 04:14:35,152 INFO: Match startup [in A:\projects\match\app\__init__.py:82]
2021-04-05 09:04:26,901 INFO: Match startup [in C:\Users\ccfra\projects\match\app\__init__.py:82]
2021-04-05 09:44:45,948 INFO: Match startup [in C:\Users\ccfra\projects\match\app\__init__.py:82]
2021-04-05 18:35:33,445 INFO: Match startup [in A:\projects\match\app\__init__.py:82]
2021-04-05 18:37:01,969 INFO: Match startup [in A:\projects\match\app\__init__.py:82]
2021-04-05 19:10:48,775 INFO: Match startup [in A:\projects\match\app\__init__.py:85]
2021-04-06 15:44:45,098 INFO: Match startup [in A:\projects\match\app\__init__.py:82]
2021-04-06 15:58:26,043 INFO: Match startup [in A:\projects\match\app\__init__.py:82]
2021-04-11 20:22:59,597 INFO: Match startup [in A:\projects\match\app\__init__.py:82]
2021-04-16 17:27:38,898 INFO: Match startup [in A:\projects\match\app\__init__.py:85]
2021-04-16 17:51:42,858 INFO: Match startup [in A:\projects\match\app\__init__.py:85]
2021-04-18 00:44:00,080 INFO: Match startup [in A:\projects\match\app\__init__.py:85]
2021-04-18 12:54:21,844 INFO: Match startup [in A:\projects\match\app\__init__.py:94]
2021-04-19 21:14:27,322 INFO: Match startup [in A:\projects\match\app\__init__.py:96]
2021-04-21 12:44:59,897 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 12:45:04,929 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 12:45:10,145 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 12:45:14,532 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 14:44:30,856 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 14:44:37,515 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 14:47:45,257 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 14:47:51,660 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 14:47:57,394 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:05:28,637 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:05:33,443 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:06:55,362 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:08:28,746 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:08:36,144 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:08:44,710 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:08:48,939 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:11:18,649 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:11:23,410 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:11:28,115 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:22:20,658 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:22:27,512 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:22:32,444 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:29:10,875 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:29:16,136 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 15:29:20,288 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 20:34:06,115 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 20:34:10,070 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
2021-04-21 20:34:14,432 INFO: Match startup [in A:\projects\match\app\__init__.py:88]
